In [3]:
import numpy as np
a = np.array([20, 40, 60, 80])
print(np.append(a,90))


[20 40 60 80 90]


In [4]:
a = np.array([[20, 40], [60, 80]])
print(np.append(a,[90, 100]))


[ 20  40  60  80  90 100]


In [5]:
a = np.array([20, 40, 60, 80])
print(np.insert(a, 1, 50)) #array, index, value

[20 50 40 60 80]


In [11]:
a = np.array([[20, 40], [60, 80]])
print(np.insert(a, 1, [50,60], axis = 1))
print(np.insert(a, 1, [50], axis = 0))
print(np.insert(a, [1,2], [50], axis = 0))

[[20 50 40]
 [60 60 80]]
[[20 40]
 [50 50]
 [60 80]]
[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [16]:
print(a)
print()
print(np.delete(a,1))
print()
print(np.delete(a, 1, axis = 0))
print()
print(np.delete(a, 1, axis = 1))

[[20 40]
 [60 80]]

[20 60 80]

[[20 40]]

[[20]
 [60]]
