In [1]:
import numpy as np
# concatenate
a = [30, 40, 50]
b = [5, 5, 3]
print(a+b)


[30, 40, 50, 5, 5, 3]


In [5]:

# Concatenate
arr1 = np.array([30, 40, 50])
arr2 = np.array([5, 5, 3])
print(np.concatenate([arr1, arr2])) 

[30 40 50  5  5  3]


In [10]:
arr1 = np.array([[30, 40], [50, 10]])
arr2 = np.array([[5, 5],[3, 3]])
print(np.concatenate([arr1, arr2], axis = 0))

print(np.concatenate([arr1, arr2], axis = 1))

print(np.hstack([arr1, arr2])) #horizontal concatenation

print(np.vstack([arr1, arr2])) #vertical concatenation



[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]
[[30 40  5  5]
 [50 10  3  3]]
[[30 40  5  5]
 [50 10  3  3]]
[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [14]:
# Splitting
a = np.array([20, 40, 30, 40, 10,20])
b = np.array_split(a, 3)
print(b[1])
b = np.array_split(a, 4)
print(b)
b = np.array_split(a, 5)
print(b)

[30 40]
[array([20, 40]), array([30, 40]), array([10]), array([20])]
[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [16]:
a = np.array([[20, 40, 30], [40, 10,20]])
b = np.array_split(a, 2)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]
