In [11]:
import numpy as np

arr1 = np.array([30, 40, 60, 20, 10])
arr2 = np.array([30, 20, 10, 10, 20])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(np.subtract(arr1, arr2))
print(arr1*arr2)
print(np.multiply(arr1, arr2))
print(arr1/arr2)
print(np.divide(arr1, arr2))

[60 60 70 30 30]
[60 60 70 30 30]
[  0  20  50  10 -10]
[  0  20  50  10 -10]
[900 800 600 200 200]
[900 800 600 200 200]
[1.  2.  6.  2.  0.5]
[1.  2.  6.  2.  0.5]


In [12]:
arr1 = np.array([[30, 40], [20, 10]])
arr2 = np.array([[30, 20], [10, 20]])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(np.subtract(arr1, arr2))
print(arr1*arr2)
print(np.multiply(arr1, arr2))
print(arr1/arr2)
print(np.divide(arr1, arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]
[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]
[[900 800]
 [200 200]]
[[900 800]
 [200 200]]
[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [18]:
arr1 = np.array([3, 4, 2, 1])
arr2 = np.array([3])
print(np.power(arr1, arr2))
print(np.sqrt(arr1))



[27 64  8  1]
[1.73205081 2.         1.41421356 1.        ]
