In [2]:
print("hello")

hello


In [8]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>
[[10 20 30 40]]


In [20]:
arr=np.array([10,20,30,40])
# slicing
# , [50, 60, 70, 80], [20, 40, 60, 80]
print(arr[0:3])
print(arr[0:])
print(arr[3:])
print(arr[:2])

[10 20 30]
[10 20 30 40]
[40]
[10 20]


In [24]:
arr=np.array([[10,20,30,40], [50, 60, 70, 80]])
print(arr[0:2, 0:2])
print(arr[0, 1:3]) #1st Array 
print(arr[1, 2:]) #second array

[[10 20]
 [50 60]]
[20 30]
[70 80]


In [29]:
arr=np.array([[10,20,30,40], [50, 60, 70, 80], [20, 40, 60, 80]])
print(arr[2,2])#thirdarray#thirdelement #indexing starts from 0


60


In [33]:
# attributes of array
arr=np.array([[10,20,30,40], [50, 60, 70, 80], [20, 40, 60, 80]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(3, 4)
12
2
int64


In [40]:
a = [[10,20,30,40], [50, 60, 70, 80]]
arr = np.array(a)
print(arr)
print(arr.shape) #rows and columns
print(len(arr)) #number of nested values
print(np.size(arr))#number of elements
print(type(arr))#type o variable
print(arr.dtype) #datatype of array
print(arr.astype(int)) #conversion of datatypes


[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
2
8
<class 'numpy.ndarray'>
int64
[[10 20 30 40]
 [50 60 70 80]]
