In [2]:
import numpy as np

ar = np.array([7, 8, 4, 12, 9])
print(np.sort(ar))
print()
ar = np.array([[7, 8, 4, 12, 9], [4, 8, 3, 1, 9]])
print(np.sort(ar))




[ 4  7  8  9 12]

[[ 4  7  8  9 12]
 [ 1  3  4  8  9]]


In [4]:
ar = np.array([7, 8, 4, 12, 9])
s = np.where(ar == 4)
print(s)
s = np.where(ar % 2 == 0)
print(s)


(array([2]),)
(array([1, 2, 3]),)


In [8]:
ar = np.array([ 4,  7,  8,  9, 12])
ss = np.searchsorted(ar, 8)
print(ss)

2


In [9]:
ar = np.array([ 4,  7,  8,  9])

fa = [True, False, True, False]
new = ar[fa]
print(new)

[4 8]


In [11]:
ar = np.array([ 4,  7,  8,  9])

fa = ar>5

new = ar[fa]
print(new)

[7 8 9]


In [12]:
ar = np.array([ 4,  7,  8,  9])

fa = ar%2 == 0

new = ar[fa]
print(new)

[4 8]
